Repository jamesAllenJahner3rd/project_manager, pull requests merged in 2025-02, with the labels that each got.

#25 Passport
  config/database.js
  config/passport.js
  controllers/profileController.js
  middleware/auth.js
  models/Profile.js
  package-lock.json
  package.json
  public/css/style.css
  routes/auth.js
  routes/indexRoutes.js
  routes/loginRoutes.js
  routes/postRoutes.js
  routes/profileRoutes.js
  server.js
  views/login.ejs
Labels: enhancement

#27 Feature/add page connections chart
  PAGE_CONNECTIONS.md
  routes/profileRoutes.js
Labels: documentation

#33 This returns a list of the project names to the profile that are associated with the user.
  routes/indexRoutes.js
Labels: enhancement

#35 Set up the projectpage to link to the project names in the profile.
  controllers/projectController.js
  views/profile.ejs
  views/project_template.ejs
Labels: enhancement

#37 Update project_template.ejs
  views/project_template.ejs
Labels: enhancement

#42 kanban documents now move
  public/css/dragula.css
  public/css/style.css
  public/js/dragula.js
  public/js/main.js
  views/project_template.ejs
Labels: enhancement

#43 removed title error, Added Delete.
  public/images/Icons1.jpg
  public/images/Icons1.webp
  public/images/Icons2.jpg
  public/images/Icons2.webp
  views/project_template.ejs
Labels: bug

#44 dblclick the column title to edit it.
  views/project_template.ejs
Labels: enhancement
